services:
  - type: web
    name: snake-backend
    env: node
    rootDir: backend
    plan: free
    buildCommand: npm install --include=dev && npm run build
    startCommand: npm run start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: FRONTEND_ORIGIN
        fromService:
          type: web
          name: snake-frontend
          property: host
      - key: BASE_API_KEY
        sync: false
      - key: ADMIN_WALLET_ADDRESS
        sync: false

  - type: web
    name: snake-frontend
    env: static
    rootDir: frontend
    buildCommand: npm install --include=dev && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: snake-backend
          property: host
      - key: VITE_RECORD_CONTRACT_ADDRESS
        value: 0x9e5d82E6B6419C066Bc57F5a70116659c468d780
      - key: VITE_PAYMASTER_URL
        sync: false
